name: React CI with Yarn

on:
  push:
    branches: [ "fe-dev" ]
  pull_request:
    branches: [ "fe-dev" ]

# 환경변수 정의
# 리전, 버킷 이름
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: hp5234-dragonmoney-front

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Node v 확인
      - name: Check Node v
        run: node -v

      # 의존 파일 설치
      - name: Install Dependencies
        run: cd client && npm install

      # React Build
      - name: Build
        run: cd client && npm run build
        env:
          CI: ""

      # Access Key와 Secret Access Key를 통해 권한을 확인합니다.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려옵니다.
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 등록한 Github Secret이 자동으로 불려옵니다.
          aws-region: ${{ env.AWS_REGION }}

      # 빌드 결과물을 S3 버킷에 업로드
      - name: Upload to AWS S3
        run: |
          aws s3 cp \
            --debug
            --recursive \
            --region ${{ env.AWS_REGION }}
            /client/build s3://${{ env.S3_BUCKET_NAME }}/